# -*- makefile -*-
#
# This file is automatically generated by configure.
# Do not hand edit.

OSTYPE		:= darwin16.0.0
MACHINETYPE	:= x86_64
PLATFORM	:= x86_64-apple-darwin16.0.0
FULLOSTYPE	:= apple-darwin16.0.0
